name: Pull Preview ðŸ‘€
run-name: Pull Preview ðŸ‘€
on:
    pull_request:
        branches: [main]
        types: [labeled, unlabeled, synchronize, closed, reopened]

concurrency: ${{ github.ref }}

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        if: github.event.label.name == 'pullpreview' || contains(github.event.pull_request.labels.*.name, 'pullpreview')
        timeout-minutes: 30
        permissions:
            contents: read
            deployments: write
            pull-requests: write
            statuses: write
        steps:
            - uses: actions/checkout@v4

            - name: Generate .env for docker-compose
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
                  echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env

            - name: Generate MongoDB keyfile
              run: |
                  openssl rand -base64 768 > docker/mongo/keyfile.txt
                  chmod 400 docker/mongo/keyfile.txt

            - uses: pullpreview/action@v5
              with:
                  always_on: main
                  label: pullpreview
                  provider: lightsail
                  instance_type: large
                  compose_files: docker/docker-compose.preview.yml
                  ttl: 48h
              env:
                  AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
                  AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
                  AWS_REGION: 'eu-central-1'
